entidad/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.home, name="home"),
    path('permiso_denegado', views.permiso_denegado, name="permiso_denegado"),

    #PRODUCTOS
    path('productos/', views.productos, name="productos"),
    path('nuevo_producto/', views.nuevo_producto, name="nuevo_producto"),
    path('modificar_producto/<int:pk>', views.modificar_producto, name="modificar_producto"),
    path('eliminar_producto/<int:pk>', views.eliminar_producto, name="eliminar_producto"),

    #CATEGORIAS
    path('categorias/', views.categorias, name='categorias'),
    path('nueva_categoria/', views.nueva_categoria, name="nueva_categoria"),
    path('modificar_categoria/<int:pk>', views.modificar_categoria, name="modificar_categoria"),
    path('eliminar_categoria/<int:pk>', views.eliminar_categoria, name="eliminar_categoria"),

    #PROVEEDORES_PRODUCTOS
    path('proveedores_producto/', views.proveedores_productos, name="proveedores_productos"),
    path('nuevo_proveedor_producto/', views.nuevo_proveedor_producto, name="nuevo_proveedor_producto"),
    path('modificar_proveedor_producto/<int:pk>', views.modificar_proveedor_producto, name="modificar_proveedor_producto"),
    path('eliminar_proveedor_producto/<int:pk>', views.eliminar_proveedor_producto, name="eliminar_proveedor_producto"),

    #CAJA
    path('caja',views.caja, name='caja'),
    path('abrir_caja/',views.abrir_caja, name='abrir_caja'),
    path('cerrar_caja/',views.cerrar_caja, name='cerrar_caja'),
    path('ingresar_dinero/',views.ingresar_dinero, name='ingresar_dinero'),
    path('retirar_dinero/',views.retirar_dinero, name='retirar_dinero'),
    path('cajas',views.cajas, name='cajas'),
    path('caja/<int:pk>/ventas', views.ventas, name='ventas'),

    #VENTA   
    path('ventas/nueva/', views.crear_venta, name='crear_venta'),
    path('venta/<int:pk>/', views.detalle_venta, name='detalle_venta'),
    path('detalle_venta_pdf/<int:pk>/', views.detalle_venta_pdf, name='detalle_venta_pdf'),
    path('ventas/', views.ventasactual, name='ventasactual'),
    path('venta_exitosa/<int:pk>/', views.venta_exitosa, name='venta_exitosa'),



    # CLIENTES
    path("clientes", views.clientes, name="clientes"),
    path('nuevo_cliente/', views.nuevo_cliente, name="nuevo_cliente"),
    path("modificar_cliente/<int:pk>",views.modificar_cliente, name="modificar_cliente"),
    path("eliminar_cliente/<int:pk>",views.eliminar_cliente, name="eliminar_cliente"),
    path('ventas_clientes/<int:pk>/ventas', views.ventas_clientes, name='ventas_clientes'),

    #LOGIN
    path("usuarios/", views.usuarios, name='usuarios'),
    path("nuevo_usuario/", views.nuevo_usuario, name='nuevo_usuario'),
    path("modificar_usuario/<int:pk>", views.modificar_usuario, name='modificar_usuario'),
    path("eliminar_usuario/<int:pk>", views.eliminar_usuario, name='eliminar_usuario'), ##CREO QUE NO IRIA EN EL SISTEMA. SOLO PARA PROBAR
    path("login/", views.user_login, name="login"),
    path("logout/", views.login_logout, name='logout'),
    path("change_password/<int:pk>", views.change_password_user, name='change_password'),
    

    
    # GRAFICOS
  
     path('Grafico_clientes/', views.clientes_mas_ventas, name="clientes_mas_ventas"),
     path('grafico_productos/', views.productos_mas_vendidos, name='productos_mas_vendidos'),

]

imet/entidad/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    #PRODUCTOS
    path('productos/', views.productos, name="productos"),
    path('nuevo_producto/', views.nuevo_producto, name="nuevo_producto"),
    path('modificar_producto/<int:pk>', views.modificar_producto, name="modificar_producto"),
    path('eliminar_producto/<int:pk>', views.eliminar_producto, name="eliminar_producto"),

    #CATEGORIAS
    path('categorias/', views.categorias, name='categorias'),
    path('nueva_categoria/', views.nueva_categoria, name="nueva_categoria"),
    path('nueva_categoria_2/', views.nueva_categoria_2, name="nueva_categoria_2"),

    path('modificar_categoria/<int:pk>', views.modificar_categoria, name="modificar_categoria"),
    path('eliminar_categoria/<int:pk>', views.eliminar_categoria, name="eliminar_categoria"),

    #PROVEEDORES_PRODUCTOS
    path('proveedores_producto/', views.proveedores_productos, name="proveedores_productos"),
    path('nuevo_proveedor_producto/', views.nuevo_proveedor_producto, name="nuevo_proveedor_producto"),
    path('modificar_proveedor_producto/<int:pk>', views.modificar_proveedor_producto, name="modificar_proveedor_producto"),
    path('eliminar_proveedor_producto/<int:pk>', views.eliminar_proveedor_producto, name="eliminar_proveedor_producto"),
    #VENTAS
    # path('proceso_venta/', views.proceso_venta, name='proceso_venta'),

    #CAJA
    path('caja',views.caja, name='caja'),
    path('abrir_caja/',views.abrir_caja, name='abrir_caja'),
    path('cerrar_caja/',views.cerrar_caja, name='cerrar_caja'),
    path('ingresar_dinero/',views.ingresar_dinero, name='ingresar_dinero'),
    path('retirar_dinero/',views.retirar_dinero, name='retirar_dinero'),
    path('cajas',views.cajas, name='cajas'),


    #VENTA PRUEBA CHAT
   path('ventas/nueva/', views.crear_venta, name='crear_venta'),


]

imet/imet/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('entidad.urls')),
]

imet/urls.py
from django.contrib import admin
from django.urls import path,include
from entidad.views import login,logout
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('entidad.urls')),
    # path('login/', login.as_view(redirect_authenticated_user=True, template_name='registration/login.html')),

    #path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout')
]

entidad/models.py
from django.db import models

from django.contrib.auth.models import User

from django.utils.timezone import datetime
ESTADOS_CHOICES=(
    ("NOP","NO PAGADO"),
    ("PAG", "PAGADO")
)

METODO_PAGO_CHOICE=(
    ("TRAN","TRANSFERENCIA"),
    ("EFEC", "EFECTIVO"),
    ("TARJ", "TARJETA")
)

class Categoria(models.Model):
    nombre= models.CharField(max_length=50, unique=True, null=False, blank=False)
    activo= models.BooleanField(default=True)
    
    class Meta:
        verbose_name = ("Categoria")
        verbose_name_plural = ("Categorias")

    def __str__(self):
        return f"{self.nombre}"


class Cliente(models.Model):
    dni= models.CharField(max_length=8)
    nombre= models.CharField(max_length=30)
    apellido= models.CharField(max_length=30)
    correo= models.EmailField(max_length=40, blank=True)
    telefono= models.CharField(max_length=10)
    activo= models.BooleanField(default=True)

    class Meta:
        verbose_name = ("Cliente")
        verbose_name_plural = ("Clientes")

    def __str__(self):
        return f"{self.nombre} {self.apellido}"

class ProveedorProducto(models.Model):
    nombre= models.CharField(max_length=100)
    telefono= models.CharField(max_length=10)
    activo= models.BooleanField(default=True)


    class Meta:
        verbose_name = ("Proveedor de producto")
        verbose_name_plural = ("Proveedores de productos")

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre= models.CharField(max_length=100, blank=False)
    marca= models.CharField(max_length=10, null=True ,blank=True)
    precio= models.DecimalField(max_digits=10, decimal_places=2)
    categoria= models.ForeignKey(Categoria, on_delete=models.PROTECT)
    descripcion= models.TextField(max_length=100, null=True, blank=True)
    cantidad=models.IntegerField(default=0)
    proveedores= models.ManyToManyField('ProveedorProducto' ,related_name='proveedores')
    activo= models.BooleanField(default=True)

    class Meta:
        verbose_name = ("Producto")
        verbose_name_plural = ("Productos")

    def __str__(self):
        return f"{self.nombre} {self.marca} {self.precio} "

class Caja(models.Model):
    empleado= models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_apertura= models.DateTimeField(auto_now_add=True)
    fecha_cierre = models.DateTimeField(null=True, blank=True)
    monto_inicial= models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_ingresado= models.DecimalField(max_digits=10, decimal_places=2, default=0)
    total_egresado= models.DecimalField(max_digits=10, decimal_places=2, default=0)
    saldo_total= models.DecimalField(max_digits=10, decimal_places=2)
    activo= models.BooleanField(default=False)

    class Meta:
        verbose_name = "Caja"
        verbose_name_plural = "Cajas"

    def __str__(self):
        return f"{self.empleado.username} {self.fecha_apertura}"


class MovimientoCaja(models.Model):
    TIPO_MOVIMIENTO = [
        ('INGRESO', 'Ingreso'),
        ('RETIRO', 'Retiro'),
        ('VENTA', 'Venta')
    ]

    caja = models.ForeignKey(Caja, on_delete=models.CASCADE, related_name="movimientos")
    empleado= models.ForeignKey(User, on_delete=models.CASCADE)
    tipo = models.CharField(max_length=7, choices=TIPO_MOVIMIENTO)
    cantidad = models.DecimalField(max_digits=10, decimal_places=2)
    fecha = models.DateTimeField(auto_now_add=True)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.tipo} de {self.cantidad} en {self.fecha}"

class Venta(models.Model):
    caja= models.ForeignKey(Caja, on_delete=models.PROTECT)
    empleado= models.ForeignKey(User, on_delete=models.PROTECT)
    cliente= models.ForeignKey(Cliente, on_delete=models.PROTECT)
    fecha= models.DateTimeField(auto_now_add=True)
    total= models.DecimalField(max_digits=10, decimal_places=2)
    estado= models.CharField(max_length=4, choices=ESTADOS_CHOICES, default="NOP")
    forma_pago = models.CharField(max_length=100,choices=METODO_PAGO_CHOICE, default="EFEC")
    descuento= models.DecimalField(max_digits=10, default=0, decimal_places=2)
    class Meta:
        verbose_name = ("Venta")
        verbose_name_plural = ("Ventas")

    def __str__(self):
        return f"{self.caja} {self.empleado.username} {self.cliente} {self.fecha} {self.total} {self.estado}"

class DetalleVenta(models.Model):
    venta= models.ForeignKey(Venta, on_delete=models.CASCADE)
    cantidad= models.IntegerField()
    sub_total= models.DecimalField(max_digits=10, decimal_places=2)
    producto= models.ManyToManyField(Producto, through='DetalleVentaXProducto')

    class Meta:
        verbose_name = ("Detalle de venta")
        verbose_name_plural = ("Detalles de ventas")

    def __str__(self):
        return f"{self.producto} {self.cantidad} {self.sub_total}"
    
class DetalleVentaXProducto(models.Model):
    detalle_venta = models.ForeignKey(DetalleVenta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT)
    cantidad= models.IntegerField(default=0)
    # AGREGAR SUBTOTAL OPCIONAL

    class Meta:
        db_table = 'entidad_detalleventa_producto'
        verbose_name = ("Detalle Venta Producto")
        verbose_name = ("Detalles Ventas Productos")
    
    def __str__(self):
        return f"{self.detalle_venta} {self.productos} {self.cantidad}"


class AccesoUsuario(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha_ingreso = models.DateField(default=datetime.now)
    hora_ingreso = models.TimeField(default=datetime.now)
    ip_address = models.CharField(max_length=30)
    tipo = models.BooleanField(default=False)
    
    class Meta:
        verbose_name = ("Acceso Usuario")
        verbose_name_plural = ("Accesos Usuarios")

    def __str__(self):
        return f"{self.usuario} {self.ip_address}"

entidad/forms.py
from django import forms
from django.forms import modelformset_factory

from entidad.models import *

class ProductoForm(forms.ModelForm):
    proveedores = forms.ModelMultipleChoiceField(
    queryset=ProveedorProducto.objects.filter(activo=True),
    widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-check'}),
    required=False
    )
    class Meta:
        model = Producto
        fields = ('nombre','marca','precio','categoria','cantidad','descripcion','proveedores')
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-styling'}),
            'marca': forms.TextInput(attrs={'class': 'form-styling'}),
            'precio': forms.NumberInput(attrs={'class': 'form-styling'}),
            'categoria': forms.Select(attrs={'class': 'form-styling'}),
            'cantidad': forms.NumberInput(attrs={'class': 'form-styling'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-styling', 'rows': 3, 'cols': 40}),

        }
        


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields= ('nombre',)

class ProveedorProductoForm(forms.ModelForm):
    telefono = forms.CharField(max_length=10, widget= forms.NumberInput(attrs={'max_length': '10', 'oninput': "this.value=this.value.slice(0,10)" , 'placeholder':'Ingrese Teléfono'}), label='Teléfono')
    nombre = forms.CharField(widget=forms.TextInput(attrs={'oninput': "this.value=this.value.replace(/[^A-Za-zÁÉÍÓÚáéíóúÑñ\\s]/g, '')",'placeholder': 'Ingrese nombre proveedor'}),label='Nombre')
    class Meta:
        model = ProveedorProducto
        fields = ('nombre', 'telefono')

class AperturaCajaForm(forms.Form):
    monto_inicial=forms.DecimalField(max_digits=10, decimal_places=2, required=True)
    

class IngresarDineroForm(forms.Form):
    tipo = forms.ChoiceField(choices=[('INGRESO', 'Ingreso')])
    cantidad=forms.DecimalField(max_digits=10,decimal_places=2, min_value=0, required=True)
    descripcion = forms.CharField(widget=forms.Textarea, required=False, label="Descripción")

class RetirarDineroForm(forms.Form):
    tipo = forms.ChoiceField(choices=[('RETIRO', 'Retiro')])
    cantidad=forms.DecimalField(max_digits=10,decimal_places=2, min_value=0, required=True)
    descripcion = forms.CharField(widget=forms.Textarea, required=False, label="Descripción")

class ClienteForm(forms.ModelForm):
    dni = forms.CharField(max_length=8, widget= forms.NumberInput(attrs={'max_length': '8', 'oninput': "this.value=this.value.slice(0,8)", 'placeholder': 'Ingrese su DNI'}), label='DNI')
    telefono = forms.CharField(max_length=10, widget= forms.NumberInput(attrs={'max_length': '10', 'oninput': "this.value=this.value.slice(0,10)" , 'placeholder':'Ingrese Teléfono'}), label='Teléfono')
    nombre = forms.CharField(widget=forms.TextInput(attrs={'oninput': "this.value=this.value.replace(/[^A-Za-zÁÉÍÓÚáéíóúÑñ\\s]/g, '')",'placeholder': 'Ingrese su nombre'}),label='Nombre')
    apellido = forms.CharField(widget=forms.TextInput(attrs={'oninput': "this.value=this.value.replace(/[^A-Za-zÁÉÍÓÚáéíóúÑñ\\s]/g, '')",'placeholder': 'Ingrese su apellido'}),label='apellido')
    correo = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Ingrese su correo electrónico'} ), label='Correo Electrónico' )
    class Meta:
        model= Cliente
        fields= ("dni","nombre","apellido","correo","telefono")

#probando formulario de registro

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'oninput': "this.value=this.value.replace(/[^A-Za-zÁÉÍÓÚáéíóúÑñ\\s]/g, '')",'placeholder': 'Ingrese su nombre'}),label='Nombre', required=True)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'oninput': "this.value=this.value.replace(/[^A-Za-zÁÉÍÓÚáéíóúÑñ\\s]/g, '')",'placeholder': 'Ingrese su apellido'}),label='apellido', required= True)
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Ingrese su correo electrónico'} ), label='Correo Electrónico', required=True)
    group = forms.ModelChoiceField(label='Tipo de usuario', queryset=Group.objects.all(), required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'group',)
class UserModifyForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'oninput': "this.value=this.value.replace(/[^A-Za-zÁÉÍÓÚáéíóúÑñ\\s]/g, '')",'placeholder': 'Ingrese su nombre'}),label='Nombre', required=True)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'oninput': "this.value=this.value.replace(/[^A-Za-zÁÉÍÓÚáéíóúÑñ\\s]/g, '')",'placeholder': 'Ingrese su apellido'}),label='apellido', required= True)
    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Ingrese su correo electrónico'} ), label='Correo Electrónico', required=True)
    group = forms.ModelChoiceField(label='Tipo de usuario', queryset=Group.objects.all(), required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'group','is_active',)

templates/entidad/abrir_caja_form.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header text-white py-2">
            <h5 class="modal-title" >Apertura de caja</h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form id="abrirCajaForm" method="post" action="{% url 'abrir_caja' %}">
              {% csrf_token %}
              <div class="mb-3" >
                {{ form.monto_inicial.label_tag }}
                <div style="margin-top: 0.5rem;">
                  {{ form.monto_inicial }}
                </div>
              </div>
            </form>
          </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" 
                    >Cancelar</button>
            <button type="submit" class="btn btn-primary" form="abrirCajaForm" 
                    >Confirmar</button>
          </div>
    </div>
</div>

templates/entidad/cajas.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/productos_tabla.css' %}">

<h1 class="products-title">REGISTRO DE CAJAS</h1>

<table class="table-custom" id="table-registrocajas">
    <thead>
        <tr>
            <th>ID</th>
            <th>EMPLEADO</th>
            <th>FECHA DE APERTURA</th>
            <th>MONTO INICIAL</th>
            <th>TOTAL INGRESADO</th>
            <th>TOTAL RETIRADO</th>
            <th>SALDO TOTAL</th>
            <th>ESTADO</th>
            <th>ACCIONES</th>
        </tr>
    </thead>
    <tbody>
        {% for caja in cajas %}
            <tr>
                <td>{{ caja.id }}</td>
                <td>{{ caja.empleado }}</td>
                <td>{{ caja.fecha_apertura }}</td>
                <td>{{ caja.monto_inicial }}</td>
                <td>{{ caja.total_ingresado }}</td>
                <td>{{ caja.total_egresado }}</td>
                <td>{{ caja.saldo_total }}</td>
                <td>
                    {% if caja.activo %}
                        ABIERTA
                    {% else %}
                        CERRADA
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'ventas' caja.id %}" class="btn btn-secondary">VER</a>
                </td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="9">No hay cajas disponibles.</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.full.min.js"></script>

<script>
    $(document).ready(function() {
        $('#table-registrocajas').DataTable({
            "paging": true,
            "ordering": true,  // Habilitar el ordenamiento
            "columnDefs": [
                { "orderable": false, "targets": [0, 1, 2, 4, 5, 8] }  // Deshabilitar el ordenamiento en todas las columnas excepto Monto Inicial (3) y Total Retirado (5)
            ],
            "searching": true,
            "lengthChange": false,
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sSearch": "Buscar:",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sPrevious": "Anterior",
                    "sNext": "Siguiente",
                    "sLast": "Último"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
    });
</script>

{% endblock %}

templates/entidad/categorias.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Categorías</title>
    <link rel="stylesheet" href="{% static 'css/categorias_tabla.css' %}">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.min.css">
</head>
<h1 class="categories-title">Categorías</h1>

<div class="messages">
    {% for message in messages %}
        <p class="alert alert-success">{{ message }}</p>
    {% endfor %}
</div>

<table id="tabla-categorias" class="table-custom">
    <thead>
        <tr>
            <th class="column-nombre">NOMBRE</th>
            {% if perms.auth.delete_categoria %}
            <th class="column-acciones">ACCIONES</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for categoria in categorias %}
        <tr>
            <td class="column-nombre">{{ categoria.nombre }}</td>
            <td class="column-acciones actions-column">
                {% if perms.auth.add_user %}
                <a href="{% url 'modificar_categoria' categoria.id %}" class="icon-container icon-edit">
                    <i class='bx bx-edit-alt'></i>
                </a>
                <a href="{% url 'eliminar_categoria' categoria.id %}" class="icon-container icon-delete">
                    <i class='bx bx-trash'></i>
                </a>
                {% endif %}
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="2">No hay categorías disponibles.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<br>
{% if perms.auth.add_user %}
<div class="btn-container">
    <a href="{% url 'nueva_categoria' %}" class="btn-add-category">
        Nueva categoría
    </a>
</div>
{% endif %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.full.min.js"></script>

<script>
    $(document).ready(function() {
        $('#tabla-categorias').DataTable({
            "paging": true,
            "ordering": true,
            "searching": true,
            "lengthChange": false,
            "columnDefs": [
                {
                    "targets": [0],  // Solo habilita el ordenamiento en la columna 'Nombre' (índice 0)
                    "orderable": true
                },
                {
                    "targets": [1],  // Deshabilita el ordenamiento en la columna 'Acciones' (índice 1)
                    "orderable": false
                }
            ],
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sSearch": "Buscar:",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sPrevious": "Anterior",
                    "sNext": "Siguiente",
                    "sLast": "Último"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
    });
</script>

{% endblock %}

templates/entidad/cerrar_caja.html
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header text-white py-2">
            <h5 class="modal-title" >Detalles de Caja</h5>
            <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body p-3">
            <div class="card mb-3">
                <div class="card-body p-3">
                    <div class="row g-2">
                        <div class="col-12">
                            <h6 class="text-muted mb-1">Saldo Total</h6>
                            <h4 class="text-primary mb-3">${{ caja.saldo_total|floatformat:2 }}</h4>
                        </div>
                        
                        <div class="col-sm-6">
                            <h6 class="text-muted mb-1">Empleado</h6>
                            <p class="mb-2">{{ caja.empleado }}</p>
                        </div>
                        
                        <div class="col-sm-6">
                            <h6 class="text-muted mb-1">Fecha Apertura</h6>
                            <p class="mb-2">{{ caja.fecha_apertura|date:"d/m/Y H:i" }}</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Formulario -->
            <form id="cerrarCajaForm" action="{% url 'cerrar_caja' %}" method="post">
                {% csrf_token %}
                
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" 
                    >Cancelar</button>
            <button type="submit" class="btn btn-primary" form="cerrarCajaForm" 
                    >Confirmar</button>
          </div>
    </div>
</div>